"""Scaffold .claude/skills/ with namespaced Claude Code skills."""

from importlib import resources
from pathlib import Path

from rich.console import Console

from klausify import __version__

console = Console()

SKILL_NAMES = [
    "review",
    "plan",
    "debug",
    "implement",
    "refactor",
    "test",
    "fix",
    "pr",
    "commit",
    "explain",
    "new-worktree",
]

VERSION_FILE = ".klausify-version"

# Filenames generated by previous klausify versions (<0.2.0) that scaffolded
# .claude/commands/. Listed explicitly so we only remove files we created and
# leave any user-authored commands alone.
LEGACY_COMMAND_FILENAMES = [
    "test.md",
    "fix.md",
    "pr.md",
    "commit.md",
    "debug.md",
    "explain.md",
    "implement.md",
    "refactor.md",
    "new-worktree.md",
    # review was scoped: pr-review-<repo>.md
]


def _skill_dir_name(repo: Path, skill: str) -> str:
    """Return the namespaced skill directory name (e.g., 'myapp-plan')."""
    return f"{repo.name}-{skill}"


def _read_version(marker_dir: Path) -> str | None:
    """Read the klausify version from a marker file in marker_dir."""
    version_path = marker_dir / VERSION_FILE
    if version_path.exists():
        return version_path.read_text().strip()
    return None


def _write_version(marker_dir: Path) -> None:
    """Write the current klausify version to the marker file."""
    (marker_dir / VERSION_FILE).write_text(__version__ + "\n")


def _migrate_legacy_commands(repo: Path) -> None:
    """Remove .claude/commands/ files generated by older klausify versions."""
    commands_dir = repo / ".claude" / "commands"
    legacy_marker = commands_dir / VERSION_FILE
    if not legacy_marker.exists():
        return

    removed: list[Path] = []
    for filename in LEGACY_COMMAND_FILENAMES:
        target = commands_dir / filename
        if target.exists():
            target.unlink()
            removed.append(target)

    legacy_review = commands_dir / f"pr-review-{repo.name}.md"
    if legacy_review.exists():
        legacy_review.unlink()
        removed.append(legacy_review)

    legacy_marker.unlink()

    try:
        commands_dir.rmdir()
    except OSError:
        pass

    for path in removed:
        console.print(f"[dim]  Removed legacy {path.relative_to(repo)}[/dim]")
    console.print(
        f"[green]✔ Migrated {len(removed)} legacy command(s) → skills.[/green]"
    )


def scaffold_skills(
    *,
    repo: Path,
    force: bool = False,
    review_template: Path | None = None,
    base_branch: str = "main",
) -> list[Path]:
    """Create .claude/skills/<repo>-<skill>/SKILL.md for each shipped skill."""
    repo = repo.resolve()
    skills_dir = repo / ".claude" / "skills"
    skills_dir.mkdir(parents=True, exist_ok=True)

    _migrate_legacy_commands(repo)

    existing_version = _read_version(skills_dir)
    if existing_version == __version__ and not force:
        console.print(
            f"[dim]Skills already up to date (v{__version__}), skipping.[/dim]"
        )
        return []

    created: list[Path] = []
    templates = resources.files("klausify").joinpath("templates/skills")

    for skill in SKILL_NAMES:
        skill_dir = skills_dir / _skill_dir_name(repo, skill)
        skill_dir.mkdir(parents=True, exist_ok=True)
        target = skill_dir / "SKILL.md"

        # The review skill alone supports a custom template override (since it
        # also receives repo-specific check enrichment via `klausify checklist`).
        if skill == "review" and review_template is not None:
            content = review_template.read_text()
        else:
            content = templates.joinpath(skill).joinpath("SKILL.md").read_text()

        content = content.replace("{{REPO}}", repo.name)
        content = content.replace("{{BASE_BRANCH}}", base_branch)

        if target.exists() and target.read_text() == content and not force:
            console.print(
                f"[dim]  {target.relative_to(repo)} unchanged, skipping.[/dim]"
            )
            continue

        target.write_text(content)
        created.append(target)
        console.print(f"[green]✔ Created {target.relative_to(repo)}[/green]")

    _write_version(skills_dir)

    if not created:
        console.print("[dim]No skill files created.[/dim]")

    return created
